export const BLACK_TIME = {}
export const WHITE_TIME = {}
export const BLACK_NAME = document.getElementById("black-name");
export const WHITE_NAME = document.getElementById("white-name");
export const BLACK_CLOCK = document.getElementById("black-clock");
export const WHITE_CLOCK = document.getElementById("white-clock");
export const WINRATE_PIE = document.getElementById("pie");
export const WINRATE_OVER = document.getElementById("pie-over");
export const WINRATE_TEXT = document.getElementById("pie-text");
export const CONFIDENCE_BLACK_TEXT = document.getElementById("black-points");
export const CONFIDENCE_WHITE_TEXT = document.getElementById("white-points");
export const CURRENT_MOVE_MARKER_ID = 'current-move-marker';
export const BLACK_IMAGE = new Image();
BLACK_IMAGE.src = 'https://ai-sensei.com/img/black_small.png'
export const WHITE_IMAGE = new Image();
WHITE_IMAGE.src = 'https://ai-sensei.com/img/white_small.png'
export const BOARD_IMAGE = new Image();
BOARD_IMAGE.src = 'https://ai-sensei.com/img/kaya14d.jpg'
